site_name: Easier WebAssembly with twr-wasm
site_url: https://twiddlingbits.dev/docsite/
repo_url: https://github.com/twiddlingbits/twr-wasm
edit_uri: 'tree/main/docs'
site_description: Documentation and examples to execute C/C++ code in a browser, using WebAssembly and clang directly.
site_dir: azure/docsite/
theme: 
  name: material  
  features:
   - navigation.tabs
   - navigation.tabs.sticky
   - content.code.copy
plugins:
  - search
  - meta-descriptions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Getting Started:
    - Installation: gettingstarted/installation.md
    - Hello World: gettingstarted/helloworld.md
    - Basic Steps: gettingstarted/basicsteps.md
    - Passing Arguments: gettingstarted/parameters.md
    - Stdin, stdout, stderr: gettingstarted/stdio.md
    - Character Encoding: gettingstarted/charencoding.md
    - Debugging: gettingstarted/debugging.md
    - Compiler, Linker, Memory: gettingstarted/compiler-opts.md
  - Examples: 
    - Overview: examples/examples-overview.md
    - hello world: examples/examples-helloworld.md
    - stdio-div: examples/examples-stdio-div.md
    - stdio-canvas: examples/examples-stdio-canvas.md
    - balls: examples/examples-balls.md
    - pong: examples/examples-pong.md
    - maze: examples/examples-maze.md
    - fft: examples/examples-fft.md
    - callC: examples/examples-callc.md
    - libc++: examples/examples-libcxx.md
  - API Reference:
    - TypeScript/JavaScript: api/api-typescript.md
    - C Localization: api/api-localization.md
    - C General: api/api-c-general.md
    - C++ with libc++: api/api-libc++.md
    - C Draw 2D: api/api-c-d2d.md
    - C Console I/O: api/api-c-con.md
    - C Standard C Library: api/api-c-stdlib.md
  - More:
    - Wasm Runtime Limitations: more/wasm-problem.md
    - SharedArrayBuffers Note: more/production.md
    - Building the Source: more/building.md

  


